### ISSUE TITLE
启动项目类型报错有点多，大佬可以看看嘛

### ISSUE THREAD

**Issue by aoxiangsky** [zhengxs2018/fullstack-app-template#2]

**Comment by zhengxs2018** [comment]
什么错误，有截图么

**Comment by aoxiangsky** [comment]
> 什么错误，有截图么

[![fHgK1O.png](https://z3.ax1x.com/2021/08/19/fHgK1O.png)](https://imgtu.com/i/fHgK1O)
[![fHgMcD.png](https://z3.ax1x.com/2021/08/19/fHgMcD.png)](https://imgtu.com/i/fHgMcD)
[![fHgu9K.png](https://z3.ax1x.com/2021/08/19/fHgu9K.png)](https://imgtu.com/i/fHgu9K)

**Comment by zhengxs2018** [comment]
我看了下，是依赖的包有不兼容更新。

你是要这个项目做什么，是学习？还是项目中使用？

如果项目中使用推荐你用，如下的框架：

- [nestjs](https://nestjs.com/)
- [midwayjs](https://midwayjs.org/)
- [eggjs](https://eggjs.org/)

如果是学习，我晚上把项目的依赖固定下就好了

**Comment by aoxiangsky** [comment]
> 我看了下，是依赖的包有不兼容更新。
> 
> 你是要这个项目做什么，是学习？还是项目中使用？
> 
> 如果项目中使用推荐你用，如下的框架：
> 
> * [nestjs](https://nestjs.com/)
> * [midwayjs](https://midwayjs.org/)
> * [eggjs](https://eggjs.org/)
> 
> 如果是学习，我晚上把项目的依赖固定下就好了

本来想着在项目中使用，不过更多的是学习，谢谢大佬！

**Comment by zhengxs2018** [comment]
前端很多项目很少有复杂的功能需求。

如果是简单的渲染 html，没有逻辑层，只想解决请求跨域问题，可以用 nginx 代理和发送 html，如 vue 项目。

如果是需要隐藏后端，前端做中间层，可以用 eggjs 这种框架。

如果是想用 typescript 写 node，可以用 midwayjs 和 nestjs

**Comment by zhengxs2018** [comment]
但如果你是抱着学习的目的，我建议你用 koa 开发。

框架

- [koa](https://www.npmjs.com/package/koa)
- [@koa/router](https://www.npmjs.com/package/@koa/router) - 官方 fork 的 koa-router 项目
- [koa-session](https://www.npmjs.com/package/koa-session)  - 会话管理
- [koa-bodyparser](https://www.npmjs.com/package/koa-bodyparser)  - POST 请求内容解析
- [koa-helmet](https://www.npmjs.com/package/koa-helmet)  - 安全配置
- [config](http://npmjs.com/package/config) - 解决不同环境的配置问题
- [prisma](https://www.prisma.io/) - 数据库链接工具

Swagger 工具

- [koa2-swagger-ui](https://www.npmjs.com/package/koa2-swagger-ui)
- [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc)

工具包

- [axios](https://www.npmjs.com/package/axios)  - 对外请求，支持 nodejs 中使用
- [lodash](https://www.npmjs.com/package/lodash)  - 函数库，支持 nodejs 中使用
- [joi](https://www.npmjs.com/package/joi)  - 数据验证

本地开发

- [node-dev](https://www.npmjs.com/package/node-dev)  - 监听文件变化，重启服务
- [ts-node-dev](https://www.npmjs.com/package/ts-node-dev)  - 如果是 ts 项目用这个
- [cross-env](https://www.npmjs.com/package/cross-env) - 跨系统设置环境变量

生产工具

- [pm2](https://www.npmjs.com/package/pm2) - 监听应用变化，重启服务，可以用 docker 代替

其他

- [mustache](https://www.npmjs.com/package/mustache) - 无逻辑，模板引擎
- [nunjucks](https://www.npmjs.com/package/nunjucks) - 模板引擎，强大，但不推荐

参考 eggjs 的目录组织或按自己的理解开发。


等你做完一个独立的项目，再从 eggjs -> midwayjs -> nestjs 顺序去看框架，学起来会轻松很多。
